### ISSUE TITLE
Stand up team review

### ISSUE THREAD

**Issue by pipe2442** [jessicafarias/Kasra-clone#1]
Jessica you did an awesome job congratulations for this project is awesome how you learned to work with SAS you remember that you should create a document to explain all the changes you have made to create this project and for the future changes that it will have, it can be useful to help others to collaborate in your project for the future, also remember the sticky function for the header and setting widths for every image. Good job!!!

**Comment by jessicafarias** [comment]
Thanks, Luis for your review, I'm working to fix everything.
